language: php
dist: trusty
sudo: false

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - dist: precise
      php: 5.3
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --no-progress --prefer-dist --ansi

script:
  - composer test
